// This file is auto-generated by @hey-api/openapi-ts

import {
  type Client,
  type ClientMeta,
  formDataBodySerializer,
  type Options as Options2,
  type RequestResult,
  type TDataShape,
  urlSearchParamsBodySerializer,
} from "./client"
import { client } from "./client.gen"
import type {
  ImagesDeleteFileData,
  ImagesDeleteFileErrors,
  ImagesDeleteFileResponses,
  ImagesDeleteItemImagesData,
  ImagesDeleteItemImagesErrors,
  ImagesDeleteItemImagesResponses,
  ImagesDownloadImageData,
  ImagesDownloadImageErrors,
  ImagesDownloadImageResponses,
  ImagesGetImageData,
  ImagesGetImageErrors,
  ImagesGetImageResponses,
  ImagesGetItemImagesData,
  ImagesGetItemImagesErrors,
  ImagesGetItemImagesResponses,
  ImagesUploadFileData,
  ImagesUploadFileErrors,
  ImagesUploadFileResponses,
  ItemsCreateItemData,
  ItemsCreateItemErrors,
  ItemsCreateItemResponses,
  ItemsDeleteItemData,
  ItemsDeleteItemErrors,
  ItemsDeleteItemResponses,
  ItemsReadItemData,
  ItemsReadItemErrors,
  ItemsReadItemResponses,
  ItemsReadItemsData,
  ItemsReadItemsErrors,
  ItemsReadItemsResponses,
  ItemsReadMyItemsData,
  ItemsReadMyItemsErrors,
  ItemsReadMyItemsResponses,
  ItemsUpdateItemData,
  ItemsUpdateItemErrors,
  ItemsUpdateItemResponses,
  LoginLoginAccessTokenData,
  LoginLoginAccessTokenErrors,
  LoginLoginAccessTokenResponses,
  LoginRecoverPasswordData,
  LoginRecoverPasswordErrors,
  LoginRecoverPasswordHtmlContentData,
  LoginRecoverPasswordHtmlContentErrors,
  LoginRecoverPasswordHtmlContentResponses,
  LoginRecoverPasswordResponses,
  LoginResetPasswordData,
  LoginResetPasswordErrors,
  LoginResetPasswordResponses,
  LoginTestTokenData,
  LoginTestTokenResponses,
  LogsClearLogsData,
  LogsClearLogsResponses,
  LogsGetLogStatsData,
  LogsGetLogStatsResponses,
  LogsGetRecentLogsData,
  LogsGetRecentLogsErrors,
  LogsGetRecentLogsResponses,
  ModelsDeleteItemModelData,
  ModelsDeleteItemModelErrors,
  ModelsDeleteItemModelResponses,
  ModelsDeleteModelData,
  ModelsDeleteModelErrors,
  ModelsDeleteModelResponses,
  ModelsDownloadModelData,
  ModelsDownloadModelErrors,
  ModelsDownloadModelResponses,
  ModelsGetModelData,
  ModelsGetModelErrors,
  ModelsGetModelResponses,
  ModelsUploadModelData,
  ModelsUploadModelErrors,
  ModelsUploadModelResponses,
  NavigationGetNavigationItemsData,
  NavigationGetNavigationItemsErrors,
  NavigationGetNavigationItemsResponses,
  NfcListTagsData,
  NfcListTagsErrors,
  NfcListTagsResponses,
  NfcListUntaggedItemsData,
  NfcListUntaggedItemsErrors,
  NfcListUntaggedItemsResponses,
  NfcRegisterTagData,
  NfcRegisterTagErrors,
  NfcRegisterTagResponses,
  NfcRevokeTagData,
  NfcRevokeTagErrors,
  NfcRevokeTagResponses,
  NfcVerifyTagData,
  NfcVerifyTagErrors,
  NfcVerifyTagResponses,
  PaymentsCreateCheckoutSessionData,
  PaymentsCreateCheckoutSessionErrors,
  PaymentsCreateCheckoutSessionResponses,
  PaymentsGetStripeConfigData,
  PaymentsGetStripeConfigResponses,
  PaymentsPaymentCancelData,
  PaymentsPaymentCancelResponses,
  PaymentsPaymentSuccessData,
  PaymentsPaymentSuccessErrors,
  PaymentsPaymentSuccessResponses,
  PaymentsStripeWebhookData,
  PaymentsStripeWebhookResponses,
  PrivateCreateUserData,
  PrivateCreateUserErrors,
  PrivateCreateUserResponses,
  UsersApiCurrentUserData,
  UsersApiCurrentUserResponses,
  UsersConfirmEmailData,
  UsersConfirmEmailErrors,
  UsersConfirmEmailResponses,
  UsersCreateUserData,
  UsersCreateUserErrors,
  UsersCreateUserResponses,
  UsersDeleteUserData,
  UsersDeleteUserErrors,
  UsersDeleteUserMeData,
  UsersDeleteUserMeResponses,
  UsersDeleteUserResponses,
  UsersGetUserEmailStatusData,
  UsersGetUserEmailStatusErrors,
  UsersGetUserEmailStatusResponses,
  UsersReadUserByIdData,
  UsersReadUserByIdErrors,
  UsersReadUserByIdResponses,
  UsersReadUserMeData,
  UsersReadUserMeResponses,
  UsersReadUsersData,
  UsersReadUsersErrors,
  UsersReadUsersResponses,
  UsersRegisterUserData,
  UsersRegisterUserErrors,
  UsersRegisterUserResponses,
  UsersUpdatePasswordMeData,
  UsersUpdatePasswordMeErrors,
  UsersUpdatePasswordMeResponses,
  UsersUpdateUserData,
  UsersUpdateUserErrors,
  UsersUpdateUserMeData,
  UsersUpdateUserMeErrors,
  UsersUpdateUserMeResponses,
  UsersUpdateUserResponses,
  UtilsListPermissionsData,
  UtilsListPermissionsResponses,
  UtilsTestEmailData,
  UtilsTestEmailErrors,
  UtilsTestEmailResponses,
} from "./types.gen"

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta
}

/**
 * Login Access Token
 *
 * OAuth2 compatible token login, get an access token for future requests
 */
export const loginLoginAccessToken = <ThrowOnError extends boolean = false>(
  options: Options<LoginLoginAccessTokenData, ThrowOnError>,
): RequestResult<
  LoginLoginAccessTokenResponses,
  LoginLoginAccessTokenErrors,
  ThrowOnError,
  "data"
> =>
  (options.client ?? client).post<
    LoginLoginAccessTokenResponses,
    LoginLoginAccessTokenErrors,
    ThrowOnError,
    "data"
  >({
    ...urlSearchParamsBodySerializer,
    responseStyle: "data",
    url: "/api/v1/login/access-token",
    ...options,
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
      ...options.headers,
    },
  })

/**
 * Test Token
 *
 * Test access token
 */
export const loginTestToken = <ThrowOnError extends boolean = false>(
  options?: Options<LoginTestTokenData, ThrowOnError>,
): RequestResult<LoginTestTokenResponses, unknown, ThrowOnError, "data"> =>
  (options?.client ?? client).post<
    LoginTestTokenResponses,
    unknown,
    ThrowOnError,
    "data"
  >({
    responseStyle: "data",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/login/test-token",
    ...options,
  })

/**
 * Recover Password
 *
 * Password Recovery
 */
export const loginRecoverPassword = <ThrowOnError extends boolean = false>(
  options: Options<LoginRecoverPasswordData, ThrowOnError>,
): RequestResult<
  LoginRecoverPasswordResponses,
  LoginRecoverPasswordErrors,
  ThrowOnError,
  "data"
> =>
  (options.client ?? client).post<
    LoginRecoverPasswordResponses,
    LoginRecoverPasswordErrors,
    ThrowOnError,
    "data"
  >({
    responseStyle: "data",
    url: "/api/v1/password-recovery/{email}",
    ...options,
  })

/**
 * Reset Password
 *
 * Reset password
 */
export const loginResetPassword = <ThrowOnError extends boolean = false>(
  options: Options<LoginResetPasswordData, ThrowOnError>,
): RequestResult<
  LoginResetPasswordResponses,
  LoginResetPasswordErrors,
  ThrowOnError,
  "data"
> =>
  (options.client ?? client).post<
    LoginResetPasswordResponses,
    LoginResetPasswordErrors,
    ThrowOnError,
    "data"
  >({
    responseStyle: "data",
    url: "/api/v1/reset-password/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Recover Password Html Content
 *
 * HTML Content for Password Recovery
 */
export const loginRecoverPasswordHtmlContent = <
  ThrowOnError extends boolean = false,
>(
  options: Options<LoginRecoverPasswordHtmlContentData, ThrowOnError>,
): RequestResult<
  LoginRecoverPasswordHtmlContentResponses,
  LoginRecoverPasswordHtmlContentErrors,
  ThrowOnError,
  "data"
> =>
  (options.client ?? client).post<
    LoginRecoverPasswordHtmlContentResponses,
    LoginRecoverPasswordHtmlContentErrors,
    ThrowOnError,
    "data"
  >({
    responseStyle: "data",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/password-recovery-html-content/{email}",
    ...options,
  })

/**
 * Read Users
 *
 * Retrieve users.
 */
export const usersReadUsers = <ThrowOnError extends boolean = false>(
  options?: Options<UsersReadUsersData, ThrowOnError>,
): RequestResult<
  UsersReadUsersResponses,
  UsersReadUsersErrors,
  ThrowOnError,
  "data"
> =>
  (options?.client ?? client).get<
    UsersReadUsersResponses,
    UsersReadUsersErrors,
    ThrowOnError,
    "data"
  >({
    responseStyle: "data",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/users/",
    ...options,
  })

/**
 * Create User
 *
 * Create new user.
 */
export const usersCreateUser = <ThrowOnError extends boolean = false>(
  options: Options<UsersCreateUserData, ThrowOnError>,
): RequestResult<
  UsersCreateUserResponses,
  UsersCreateUserErrors,
  ThrowOnError,
  "data"
> =>
  (options.client ?? client).post<
    UsersCreateUserResponses,
    UsersCreateUserErrors,
    ThrowOnError,
    "data"
  >({
    responseStyle: "data",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/users/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Delete User Me
 *
 * Delete own user.
 */
export const usersDeleteUserMe = <ThrowOnError extends boolean = false>(
  options?: Options<UsersDeleteUserMeData, ThrowOnError>,
): RequestResult<UsersDeleteUserMeResponses, unknown, ThrowOnError, "data"> =>
  (options?.client ?? client).delete<
    UsersDeleteUserMeResponses,
    unknown,
    ThrowOnError,
    "data"
  >({
    responseStyle: "data",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/users/me",
    ...options,
  })

/**
 * Read User Me
 *
 * Get current user.
 */
export const usersReadUserMe = <ThrowOnError extends boolean = false>(
  options?: Options<UsersReadUserMeData, ThrowOnError>,
): RequestResult<UsersReadUserMeResponses, unknown, ThrowOnError, "data"> =>
  (options?.client ?? client).get<
    UsersReadUserMeResponses,
    unknown,
    ThrowOnError,
    "data"
  >({
    responseStyle: "data",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/users/me",
    ...options,
  })

/**
 * Update User Me
 *
 * Update own user.
 */
export const usersUpdateUserMe = <ThrowOnError extends boolean = false>(
  options: Options<UsersUpdateUserMeData, ThrowOnError>,
): RequestResult<
  UsersUpdateUserMeResponses,
  UsersUpdateUserMeErrors,
  ThrowOnError,
  "data"
> =>
  (options.client ?? client).patch<
    UsersUpdateUserMeResponses,
    UsersUpdateUserMeErrors,
    ThrowOnError,
    "data"
  >({
    responseStyle: "data",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/users/me",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Update Password Me
 *
 * Update own password.
 */
export const usersUpdatePasswordMe = <ThrowOnError extends boolean = false>(
  options: Options<UsersUpdatePasswordMeData, ThrowOnError>,
): RequestResult<
  UsersUpdatePasswordMeResponses,
  UsersUpdatePasswordMeErrors,
  ThrowOnError,
  "data"
> =>
  (options.client ?? client).patch<
    UsersUpdatePasswordMeResponses,
    UsersUpdatePasswordMeErrors,
    ThrowOnError,
    "data"
  >({
    responseStyle: "data",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/users/me/password",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Register User
 *
 * Create new user without the need to be logged in.
 */
export const usersRegisterUser = <ThrowOnError extends boolean = false>(
  options: Options<UsersRegisterUserData, ThrowOnError>,
): RequestResult<
  UsersRegisterUserResponses,
  UsersRegisterUserErrors,
  ThrowOnError,
  "data"
> =>
  (options.client ?? client).post<
    UsersRegisterUserResponses,
    UsersRegisterUserErrors,
    ThrowOnError,
    "data"
  >({
    responseStyle: "data",
    url: "/api/v1/users/signup",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Confirm Email
 *
 * Confirm user email address and activate account.
 */
export const usersConfirmEmail = <ThrowOnError extends boolean = false>(
  options: Options<UsersConfirmEmailData, ThrowOnError>,
): RequestResult<
  UsersConfirmEmailResponses,
  UsersConfirmEmailErrors,
  ThrowOnError,
  "data"
> =>
  (options.client ?? client).post<
    UsersConfirmEmailResponses,
    UsersConfirmEmailErrors,
    ThrowOnError,
    "data"
  >({
    responseStyle: "data",
    url: "/api/v1/users/confirm-email",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Delete User
 *
 * Delete a user.
 */
export const usersDeleteUser = <ThrowOnError extends boolean = false>(
  options: Options<UsersDeleteUserData, ThrowOnError>,
): RequestResult<
  UsersDeleteUserResponses,
  UsersDeleteUserErrors,
  ThrowOnError,
  "data"
> =>
  (options.client ?? client).delete<
    UsersDeleteUserResponses,
    UsersDeleteUserErrors,
    ThrowOnError,
    "data"
  >({
    responseStyle: "data",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/users/{user_id}",
    ...options,
  })

/**
 * Read User By Id
 *
 * Get a specific user by id.
 */
export const usersReadUserById = <ThrowOnError extends boolean = false>(
  options: Options<UsersReadUserByIdData, ThrowOnError>,
): RequestResult<
  UsersReadUserByIdResponses,
  UsersReadUserByIdErrors,
  ThrowOnError,
  "data"
> =>
  (options.client ?? client).get<
    UsersReadUserByIdResponses,
    UsersReadUserByIdErrors,
    ThrowOnError,
    "data"
  >({
    responseStyle: "data",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/users/{user_id}",
    ...options,
  })

/**
 * Update User
 *
 * Update a user.
 */
export const usersUpdateUser = <ThrowOnError extends boolean = false>(
  options: Options<UsersUpdateUserData, ThrowOnError>,
): RequestResult<
  UsersUpdateUserResponses,
  UsersUpdateUserErrors,
  ThrowOnError,
  "data"
> =>
  (options.client ?? client).patch<
    UsersUpdateUserResponses,
    UsersUpdateUserErrors,
    ThrowOnError,
    "data"
  >({
    responseStyle: "data",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/users/{user_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Get User Email Status
 *
 * Get the most recent email log for a user.
 * Returns None if no emails have been sent.
 */
export const usersGetUserEmailStatus = <ThrowOnError extends boolean = false>(
  options: Options<UsersGetUserEmailStatusData, ThrowOnError>,
): RequestResult<
  UsersGetUserEmailStatusResponses,
  UsersGetUserEmailStatusErrors,
  ThrowOnError,
  "data"
> =>
  (options.client ?? client).get<
    UsersGetUserEmailStatusResponses,
    UsersGetUserEmailStatusErrors,
    ThrowOnError,
    "data"
  >({
    responseStyle: "data",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/users/{user_id}/email-status",
    ...options,
  })

/**
 * Test Email
 *
 * Test emails.
 */
export const utilsTestEmail = <ThrowOnError extends boolean = false>(
  options: Options<UtilsTestEmailData, ThrowOnError>,
): RequestResult<
  UtilsTestEmailResponses,
  UtilsTestEmailErrors,
  ThrowOnError,
  "data"
> =>
  (options.client ?? client).post<
    UtilsTestEmailResponses,
    UtilsTestEmailErrors,
    ThrowOnError,
    "data"
  >({
    responseStyle: "data",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/utils/test-email/",
    ...options,
  })

/**
 * List Permissions
 *
 * Return available user-permission strings.
 */
export const utilsListPermissions = <ThrowOnError extends boolean = false>(
  options?: Options<UtilsListPermissionsData, ThrowOnError>,
): RequestResult<
  UtilsListPermissionsResponses,
  unknown,
  ThrowOnError,
  "data"
> =>
  (options?.client ?? client).get<
    UtilsListPermissionsResponses,
    unknown,
    ThrowOnError,
    "data"
  >({
    responseStyle: "data",
    url: "/api/v1/utils/permissions/",
    ...options,
  })

/**
 * Read Items
 *
 * Retrieve items.
 */
export const itemsReadItems = <ThrowOnError extends boolean = false>(
  options?: Options<ItemsReadItemsData, ThrowOnError>,
): RequestResult<
  ItemsReadItemsResponses,
  ItemsReadItemsErrors,
  ThrowOnError,
  "data"
> =>
  (options?.client ?? client).get<
    ItemsReadItemsResponses,
    ItemsReadItemsErrors,
    ThrowOnError,
    "data"
  >({
    responseStyle: "data",
    url: "/api/v1/items/",
    ...options,
  })

/**
 * Create Item
 *
 * Create new item.
 */
export const itemsCreateItem = <ThrowOnError extends boolean = false>(
  options: Options<ItemsCreateItemData, ThrowOnError>,
): RequestResult<
  ItemsCreateItemResponses,
  ItemsCreateItemErrors,
  ThrowOnError,
  "data"
> =>
  (options.client ?? client).post<
    ItemsCreateItemResponses,
    ItemsCreateItemErrors,
    ThrowOnError,
    "data"
  >({
    responseStyle: "data",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/items/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Read My Items
 *
 * Retrieve items for the current user.
 */
export const itemsReadMyItems = <ThrowOnError extends boolean = false>(
  options?: Options<ItemsReadMyItemsData, ThrowOnError>,
): RequestResult<
  ItemsReadMyItemsResponses,
  ItemsReadMyItemsErrors,
  ThrowOnError,
  "data"
> =>
  (options?.client ?? client).get<
    ItemsReadMyItemsResponses,
    ItemsReadMyItemsErrors,
    ThrowOnError,
    "data"
  >({
    responseStyle: "data",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/items/my-items/",
    ...options,
  })

/**
 * Delete Item
 *
 * Delete an item and its associated images.
 */
export const itemsDeleteItem = <ThrowOnError extends boolean = false>(
  options: Options<ItemsDeleteItemData, ThrowOnError>,
): RequestResult<
  ItemsDeleteItemResponses,
  ItemsDeleteItemErrors,
  ThrowOnError,
  "data"
> =>
  (options.client ?? client).delete<
    ItemsDeleteItemResponses,
    ItemsDeleteItemErrors,
    ThrowOnError,
    "data"
  >({
    responseStyle: "data",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/items/{id}",
    ...options,
  })

/**
 * Read Item
 *
 * Get item by ID with edit permissions.
 */
export const itemsReadItem = <ThrowOnError extends boolean = false>(
  options: Options<ItemsReadItemData, ThrowOnError>,
): RequestResult<
  ItemsReadItemResponses,
  ItemsReadItemErrors,
  ThrowOnError,
  "data"
> =>
  (options.client ?? client).get<
    ItemsReadItemResponses,
    ItemsReadItemErrors,
    ThrowOnError,
    "data"
  >({
    responseStyle: "data",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/items/{id}",
    ...options,
  })

/**
 * Update Item
 *
 * Update an item.
 */
export const itemsUpdateItem = <ThrowOnError extends boolean = false>(
  options: Options<ItemsUpdateItemData, ThrowOnError>,
): RequestResult<
  ItemsUpdateItemResponses,
  ItemsUpdateItemErrors,
  ThrowOnError,
  "data"
> =>
  (options.client ?? client).put<
    ItemsUpdateItemResponses,
    ItemsUpdateItemErrors,
    ThrowOnError,
    "data"
  >({
    responseStyle: "data",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/items/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Upload File
 *
 * Upload an image for an item.
 */
export const imagesUploadFile = <ThrowOnError extends boolean = false>(
  options: Options<ImagesUploadFileData, ThrowOnError>,
): RequestResult<
  ImagesUploadFileResponses,
  ImagesUploadFileErrors,
  ThrowOnError,
  "data"
> =>
  (options.client ?? client).post<
    ImagesUploadFileResponses,
    ImagesUploadFileErrors,
    ThrowOnError,
    "data"
  >({
    ...formDataBodySerializer,
    responseStyle: "data",
    url: "/api/v1/images/{id}",
    ...options,
    headers: {
      "Content-Type": null,
      ...options.headers,
    },
  })

/**
 * Delete File
 *
 * Delete an image by its ID.
 */
export const imagesDeleteFile = <ThrowOnError extends boolean = false>(
  options: Options<ImagesDeleteFileData, ThrowOnError>,
): RequestResult<
  ImagesDeleteFileResponses,
  ImagesDeleteFileErrors,
  ThrowOnError,
  "data"
> =>
  (options.client ?? client).delete<
    ImagesDeleteFileResponses,
    ImagesDeleteFileErrors,
    ThrowOnError,
    "data"
  >({
    responseStyle: "data",
    url: "/api/v1/images/{image_id}",
    ...options,
  })

/**
 * Get Image
 *
 * Get image metadata by ID.
 */
export const imagesGetImage = <ThrowOnError extends boolean = false>(
  options: Options<ImagesGetImageData, ThrowOnError>,
): RequestResult<
  ImagesGetImageResponses,
  ImagesGetImageErrors,
  ThrowOnError,
  "data"
> =>
  (options.client ?? client).get<
    ImagesGetImageResponses,
    ImagesGetImageErrors,
    ThrowOnError,
    "data"
  >({
    responseStyle: "data",
    url: "/api/v1/images/{image_id}",
    ...options,
  })

/**
 * Delete Item Images
 *
 * Delete all images for an item.
 */
export const imagesDeleteItemImages = <ThrowOnError extends boolean = false>(
  options: Options<ImagesDeleteItemImagesData, ThrowOnError>,
): RequestResult<
  ImagesDeleteItemImagesResponses,
  ImagesDeleteItemImagesErrors,
  ThrowOnError,
  "data"
> =>
  (options.client ?? client).delete<
    ImagesDeleteItemImagesResponses,
    ImagesDeleteItemImagesErrors,
    ThrowOnError,
    "data"
  >({
    responseStyle: "data",
    url: "/api/v1/images/item/{item_id}",
    ...options,
  })

/**
 * Get Item Images
 *
 * Get all images for an item.
 */
export const imagesGetItemImages = <ThrowOnError extends boolean = false>(
  options: Options<ImagesGetItemImagesData, ThrowOnError>,
): RequestResult<
  ImagesGetItemImagesResponses,
  ImagesGetItemImagesErrors,
  ThrowOnError,
  "data"
> =>
  (options.client ?? client).get<
    ImagesGetItemImagesResponses,
    ImagesGetItemImagesErrors,
    ThrowOnError,
    "data"
  >({
    responseStyle: "data",
    url: "/api/v1/images/item/{item_id}",
    ...options,
  })

/**
 * Download Image
 *
 * Download image file by ID.
 */
export const imagesDownloadImage = <ThrowOnError extends boolean = false>(
  options: Options<ImagesDownloadImageData, ThrowOnError>,
): RequestResult<
  ImagesDownloadImageResponses,
  ImagesDownloadImageErrors,
  ThrowOnError,
  "data"
> =>
  (options.client ?? client).get<
    ImagesDownloadImageResponses,
    ImagesDownloadImageErrors,
    ThrowOnError,
    "data"
  >({
    responseStyle: "data",
    url: "/api/v1/images/download/{image_id}",
    ...options,
  })

/**
 * Get Recent Logs
 *
 * Get recent application logs (superuser only).
 *
 * Args:
 * limit: Maximum number of log entries to return (default 100, max 1000)
 * level: Filter by log level (DEBUG, INFO, WARNING, ERROR, CRITICAL)
 */
export const logsGetRecentLogs = <ThrowOnError extends boolean = false>(
  options?: Options<LogsGetRecentLogsData, ThrowOnError>,
): RequestResult<
  LogsGetRecentLogsResponses,
  LogsGetRecentLogsErrors,
  ThrowOnError,
  "data"
> =>
  (options?.client ?? client).get<
    LogsGetRecentLogsResponses,
    LogsGetRecentLogsErrors,
    ThrowOnError,
    "data"
  >({
    responseStyle: "data",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/logs/recent",
    ...options,
  })

/**
 * Clear Logs
 *
 * Clear the log buffer (superuser only).
 */
export const logsClearLogs = <ThrowOnError extends boolean = false>(
  options?: Options<LogsClearLogsData, ThrowOnError>,
): RequestResult<LogsClearLogsResponses, unknown, ThrowOnError, "data"> =>
  (options?.client ?? client).delete<
    LogsClearLogsResponses,
    unknown,
    ThrowOnError,
    "data"
  >({
    responseStyle: "data",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/logs/clear",
    ...options,
  })

/**
 * Get Log Stats
 *
 * Get log statistics (superuser only).
 */
export const logsGetLogStats = <ThrowOnError extends boolean = false>(
  options?: Options<LogsGetLogStatsData, ThrowOnError>,
): RequestResult<LogsGetLogStatsResponses, unknown, ThrowOnError, "data"> =>
  (options?.client ?? client).get<
    LogsGetLogStatsResponses,
    unknown,
    ThrowOnError,
    "data"
  >({
    responseStyle: "data",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/logs/stats",
    ...options,
  })

/**
 * Get Model
 *
 * Get model filename for an item (note: simplified implementation).
 */
export const modelsGetModel = <ThrowOnError extends boolean = false>(
  options: Options<ModelsGetModelData, ThrowOnError>,
): RequestResult<
  ModelsGetModelResponses,
  ModelsGetModelErrors,
  ThrowOnError,
  "data"
> =>
  (options.client ?? client).get<
    ModelsGetModelResponses,
    ModelsGetModelErrors,
    ThrowOnError,
    "data"
  >({
    responseStyle: "data",
    url: "/api/v1/models/{item_id}/{user_id}",
    ...options,
  })

/**
 * Upload Model
 *
 * Upload a 3D model file (.3mf) and return the URL.
 */
export const modelsUploadModel = <ThrowOnError extends boolean = false>(
  options: Options<ModelsUploadModelData, ThrowOnError>,
): RequestResult<
  ModelsUploadModelResponses,
  ModelsUploadModelErrors,
  ThrowOnError,
  "data"
> =>
  (options.client ?? client).post<
    ModelsUploadModelResponses,
    ModelsUploadModelErrors,
    ThrowOnError,
    "data"
  >({
    ...formDataBodySerializer,
    responseStyle: "data",
    url: "/api/v1/models/{item_id}/{user_id}",
    ...options,
    headers: {
      "Content-Type": null,
      ...options.headers,
    },
  })

/**
 * Delete Model
 *
 * Delete a model file by filename (supports both local and BunnyCDN).
 */
export const modelsDeleteModel = <ThrowOnError extends boolean = false>(
  options: Options<ModelsDeleteModelData, ThrowOnError>,
): RequestResult<
  ModelsDeleteModelResponses,
  ModelsDeleteModelErrors,
  ThrowOnError,
  "data"
> =>
  (options.client ?? client).delete<
    ModelsDeleteModelResponses,
    ModelsDeleteModelErrors,
    ThrowOnError,
    "data"
  >({
    responseStyle: "data",
    url: "/api/v1/models/{item_id}/{user_id}/{file_name}",
    ...options,
  })

/**
 * Download Model
 *
 * Download a model file by filename.
 */
export const modelsDownloadModel = <ThrowOnError extends boolean = false>(
  options: Options<ModelsDownloadModelData, ThrowOnError>,
): RequestResult<
  ModelsDownloadModelResponses,
  ModelsDownloadModelErrors,
  ThrowOnError,
  "data"
> =>
  (options.client ?? client).get<
    ModelsDownloadModelResponses,
    ModelsDownloadModelErrors,
    ThrowOnError,
    "data"
  >({
    responseStyle: "data",
    url: "/api/v1/models/{item_id}/{user_id}/{file_name}",
    ...options,
  })

/**
 * Delete Item Model
 *
 * Delete all model files for an item (note: this endpoint may need refinement for BunnyCDN).
 */
export const modelsDeleteItemModel = <ThrowOnError extends boolean = false>(
  options: Options<ModelsDeleteItemModelData, ThrowOnError>,
): RequestResult<
  ModelsDeleteItemModelResponses,
  ModelsDeleteItemModelErrors,
  ThrowOnError,
  "data"
> =>
  (options.client ?? client).delete<
    ModelsDeleteItemModelResponses,
    ModelsDeleteItemModelErrors,
    ThrowOnError,
    "data"
  >({
    responseStyle: "data",
    url: "/api/v1/models/{item_id}",
    ...options,
  })

/**
 * Create Checkout Session
 *
 * Create a Stripe checkout session for purchasing a model.
 */
export const paymentsCreateCheckoutSession = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PaymentsCreateCheckoutSessionData, ThrowOnError>,
): RequestResult<
  PaymentsCreateCheckoutSessionResponses,
  PaymentsCreateCheckoutSessionErrors,
  ThrowOnError,
  "data"
> =>
  (options.client ?? client).post<
    PaymentsCreateCheckoutSessionResponses,
    PaymentsCreateCheckoutSessionErrors,
    ThrowOnError,
    "data"
  >({
    responseStyle: "data",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/payments/create-checkout-session",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Payment Success
 *
 * Handle successful payment and provide secure download link.
 */
export const paymentsPaymentSuccess = <ThrowOnError extends boolean = false>(
  options: Options<PaymentsPaymentSuccessData, ThrowOnError>,
): RequestResult<
  PaymentsPaymentSuccessResponses,
  PaymentsPaymentSuccessErrors,
  ThrowOnError,
  "data"
> =>
  (options.client ?? client).get<
    PaymentsPaymentSuccessResponses,
    PaymentsPaymentSuccessErrors,
    ThrowOnError,
    "data"
  >({
    responseStyle: "data",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/payments/success",
    ...options,
  })

/**
 * Payment Cancel
 *
 * Handle payment cancellation.
 */
export const paymentsPaymentCancel = <ThrowOnError extends boolean = false>(
  options?: Options<PaymentsPaymentCancelData, ThrowOnError>,
): RequestResult<
  PaymentsPaymentCancelResponses,
  unknown,
  ThrowOnError,
  "data"
> =>
  (options?.client ?? client).get<
    PaymentsPaymentCancelResponses,
    unknown,
    ThrowOnError,
    "data"
  >({
    responseStyle: "data",
    url: "/api/v1/payments/cancel",
    ...options,
  })

/**
 * Stripe Webhook
 *
 * Handle Stripe webhook events (optional - for additional security and logging).
 */
export const paymentsStripeWebhook = <ThrowOnError extends boolean = false>(
  options?: Options<PaymentsStripeWebhookData, ThrowOnError>,
): RequestResult<
  PaymentsStripeWebhookResponses,
  unknown,
  ThrowOnError,
  "data"
> =>
  (options?.client ?? client).post<
    PaymentsStripeWebhookResponses,
    unknown,
    ThrowOnError,
    "data"
  >({
    responseStyle: "data",
    url: "/api/v1/payments/webhook",
    ...options,
  })

/**
 * Get Stripe Config
 *
 * Get Stripe publishable key for frontend.
 */
export const paymentsGetStripeConfig = <ThrowOnError extends boolean = false>(
  options?: Options<PaymentsGetStripeConfigData, ThrowOnError>,
): RequestResult<
  PaymentsGetStripeConfigResponses,
  unknown,
  ThrowOnError,
  "data"
> =>
  (options?.client ?? client).get<
    PaymentsGetStripeConfigResponses,
    unknown,
    ThrowOnError,
    "data"
  >({
    responseStyle: "data",
    url: "/api/v1/payments/config",
    ...options,
  })

/**
 * Get Navigation Items
 *
 * Return navigation items appropriate for the current (optional) user.
 */
export const navigationGetNavigationItems = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<NavigationGetNavigationItemsData, ThrowOnError>,
): RequestResult<
  NavigationGetNavigationItemsResponses,
  NavigationGetNavigationItemsErrors,
  ThrowOnError,
  "data"
> =>
  (options?.client ?? client).get<
    NavigationGetNavigationItemsResponses,
    NavigationGetNavigationItemsErrors,
    ThrowOnError,
    "data"
  >({
    responseStyle: "data",
    url: "/api/v1/navigation/",
    ...options,
  })

/**
 * Verify Tag
 *
 * Validate an NTAG 424 DNA tap (SDM/SUN) and redirect to the item page.
 *
 * Public endpoint: NFC taps arrive as plain browser GETs from the tag's
 * mirrored URL. The UID travels in plaintext (written at programming time)
 * so per-tag keys can be derived; authenticity comes from the encrypted
 * PICC data and the CMAC, which only the genuine tag can produce.
 */
export const nfcVerifyTag = <ThrowOnError extends boolean = false>(
  options: Options<NfcVerifyTagData, ThrowOnError>,
): RequestResult<
  NfcVerifyTagResponses,
  NfcVerifyTagErrors,
  ThrowOnError,
  "data"
> =>
  (options.client ?? client).get<
    NfcVerifyTagResponses,
    NfcVerifyTagErrors,
    ThrowOnError,
    "data"
  >({
    responseStyle: "data",
    url: "/api/v1/nfc/verify",
    ...options,
  })

/**
 * List Tags
 *
 * List registered NFC tags. Superuser only.
 */
export const nfcListTags = <ThrowOnError extends boolean = false>(
  options?: Options<NfcListTagsData, ThrowOnError>,
): RequestResult<
  NfcListTagsResponses,
  NfcListTagsErrors,
  ThrowOnError,
  "data"
> =>
  (options?.client ?? client).get<
    NfcListTagsResponses,
    NfcListTagsErrors,
    ThrowOnError,
    "data"
  >({
    responseStyle: "data",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/nfc/tags",
    ...options,
  })

/**
 * Register Tag
 *
 * Register a tag (bind its UID to an item). Superuser only.
 *
 * Keys are not stored here — derive them offline with
 * `uv run python -m app.nfc_provisioning <UID>` when programming the tag.
 */
export const nfcRegisterTag = <ThrowOnError extends boolean = false>(
  options: Options<NfcRegisterTagData, ThrowOnError>,
): RequestResult<
  NfcRegisterTagResponses,
  NfcRegisterTagErrors,
  ThrowOnError,
  "data"
> =>
  (options.client ?? client).post<
    NfcRegisterTagResponses,
    NfcRegisterTagErrors,
    ThrowOnError,
    "data"
  >({
    responseStyle: "data",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/nfc/tags",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * List Untagged Items
 *
 * List items that have no NFC tag registered. Superuser only.
 */
export const nfcListUntaggedItems = <ThrowOnError extends boolean = false>(
  options?: Options<NfcListUntaggedItemsData, ThrowOnError>,
): RequestResult<
  NfcListUntaggedItemsResponses,
  NfcListUntaggedItemsErrors,
  ThrowOnError,
  "data"
> =>
  (options?.client ?? client).get<
    NfcListUntaggedItemsResponses,
    NfcListUntaggedItemsErrors,
    ThrowOnError,
    "data"
  >({
    responseStyle: "data",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/nfc/untagged-items",
    ...options,
  })

/**
 * Revoke Tag
 *
 * Revoke a tag so future taps fail verification. Superuser only.
 */
export const nfcRevokeTag = <ThrowOnError extends boolean = false>(
  options: Options<NfcRevokeTagData, ThrowOnError>,
): RequestResult<
  NfcRevokeTagResponses,
  NfcRevokeTagErrors,
  ThrowOnError,
  "data"
> =>
  (options.client ?? client).delete<
    NfcRevokeTagResponses,
    NfcRevokeTagErrors,
    ThrowOnError,
    "data"
  >({
    responseStyle: "data",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/nfc/tags/{uid}",
    ...options,
  })

/**
 * Create User
 *
 * Create a new user.
 */
export const privateCreateUser = <ThrowOnError extends boolean = false>(
  options: Options<PrivateCreateUserData, ThrowOnError>,
): RequestResult<
  PrivateCreateUserResponses,
  PrivateCreateUserErrors,
  ThrowOnError,
  "data"
> =>
  (options.client ?? client).post<
    PrivateCreateUserResponses,
    PrivateCreateUserErrors,
    ThrowOnError,
    "data"
  >({
    responseStyle: "data",
    url: "/api/v1/private/users/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Api Current User
 *
 * Return the authenticated user (used by React app).
 */
export const usersApiCurrentUser = <ThrowOnError extends boolean = false>(
  options?: Options<UsersApiCurrentUserData, ThrowOnError>,
): RequestResult<UsersApiCurrentUserResponses, unknown, ThrowOnError, "data"> =>
  (options?.client ?? client).get<
    UsersApiCurrentUserResponses,
    unknown,
    ThrowOnError,
    "data"
  >({
    responseStyle: "data",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/currentUser",
    ...options,
  })
