// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {})
}

/**
 * Body_images-upload_file
 */
export type BodyImagesUploadFile = {
  /**
   * File
   */
  file: Blob | File
}

/**
 * Body_login-login_access_token
 */
export type BodyLoginLoginAccessToken = {
  /**
   * Grant Type
   */
  grant_type?: string | null
  /**
   * Username
   */
  username: string
  /**
   * Password
   */
  password: string
  /**
   * Scope
   */
  scope?: string
  /**
   * Client Id
   */
  client_id?: string | null
  /**
   * Client Secret
   */
  client_secret?: string | null
}

/**
 * Body_models-upload_model
 */
export type BodyModelsUploadModel = {
  /**
   * File
   */
  file: Blob | File
}

/**
 * CheckoutRequest
 */
export type CheckoutRequest = {
  /**
   * Item Id
   */
  item_id: string
  /**
   * Success Url
   */
  success_url?: string | null
  /**
   * Cancel Url
   */
  cancel_url?: string | null
}

/**
 * CheckoutResponse
 */
export type CheckoutResponse = {
  /**
   * Url
   */
  url: string
}

/**
 * EmailConfirmation
 */
export type EmailConfirmation = {
  /**
   * Token
   */
  token: string
}

/**
 * EmailLogPublic
 */
export type EmailLogPublic = {
  /**
   * Email To
   */
  email_to: string
  /**
   * Email Type
   */
  email_type: string
  /**
   * Subject
   */
  subject: string
  /**
   * Status
   */
  status: string
  /**
   * Error Message
   */
  error_message?: string | null
  /**
   * Id
   */
  id: string
  /**
   * User Id
   */
  user_id: string | null
  /**
   * Created At
   */
  created_at: string
  /**
   * Sent At
   */
  sent_at: string | null
}

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>
}

/**
 * ImagePublic
 */
export type ImagePublic = {
  /**
   * Path
   */
  path: string
  /**
   * Name
   */
  name: string
  /**
   * Item Id
   */
  item_id: string
  /**
   * Id
   */
  id: string
  /**
   * Created At
   */
  created_at: string
}

/**
 * ImagesPublic
 */
export type ImagesPublic = {
  /**
   * Data
   */
  data: Array<ImagePublic>
  /**
   * Count
   */
  count: number
}

/**
 * ItemCreate
 */
export type ItemCreate = {
  /**
   * Title
   */
  title: string
  /**
   * Description
   */
  description?: string | null
  /**
   * Images
   */
  images?: string | null
  /**
   * Model
   */
  model?: string | null
  /**
   * Certificate
   */
  certificate?: string | null
  /**
   * Price
   */
  price?: number
  /**
   * Is Sold
   */
  is_sold?: boolean
  /**
   * Is Original
   */
  is_original?: boolean
  /**
   * Variant Of
   */
  variant_of?: string | null
}

/**
 * ItemPublic
 */
export type ItemPublic = {
  /**
   * Title
   */
  title: string
  /**
   * Description
   */
  description?: string | null
  /**
   * Images
   */
  images?: string | null
  /**
   * Model
   */
  model?: string | null
  /**
   * Certificate
   */
  certificate?: string | null
  /**
   * Price
   */
  price?: number
  /**
   * Is Sold
   */
  is_sold?: boolean
  /**
   * Is Original
   */
  is_original?: boolean
  /**
   * Variant Of
   */
  variant_of?: string | null
  /**
   * Id
   */
  id: string
  /**
   * Owner Id
   */
  owner_id: string
  /**
   * Image Urls
   */
  image_urls?: Array<string>
}

/**
 * ItemUpdate
 */
export type ItemUpdate = {
  /**
   * Title
   */
  title?: string | null
  /**
   * Description
   */
  description?: string | null
  /**
   * Images
   */
  images?: string | null
  /**
   * Model
   */
  model?: string | null
  /**
   * Certificate
   */
  certificate?: string | null
  /**
   * Price
   */
  price?: number | null
  /**
   * Is Sold
   */
  is_sold?: boolean | null
  /**
   * Is Original
   */
  is_original?: boolean
  /**
   * Variant Of
   */
  variant_of?: string | null
}

/**
 * ItemWithPermissions
 *
 * Item data with edit permissions
 */
export type ItemWithPermissions = {
  item: ItemPublic
  /**
   * Can Edit
   */
  can_edit?: boolean
}

/**
 * ItemsPublic
 */
export type ItemsPublic = {
  /**
   * Data
   */
  data: Array<ItemPublic>
  /**
   * Count
   */
  count: number
}

/**
 * Message
 */
export type Message = {
  /**
   * Message
   */
  message: string
}

/**
 * NavigationItem
 */
export type NavigationItem = {
  /**
   * Title
   */
  title: string
  /**
   * Path
   */
  path: string
  /**
   * Icon
   */
  icon: string
  /**
   * Action
   */
  action: string | null
}

/**
 * NewPassword
 */
export type NewPassword = {
  /**
   * Token
   */
  token: string
  /**
   * New Password
   */
  new_password: string
}

/**
 * NfcTagCreate
 */
export type NfcTagCreate = {
  /**
   * Uid
   */
  uid: string
  /**
   * Item Id
   */
  item_id: string
}

/**
 * NfcTagPublic
 */
export type NfcTagPublic = {
  /**
   * Uid
   */
  uid: string
  /**
   * Item Id
   */
  item_id: string
  /**
   * Id
   */
  id: string
  /**
   * Last Read Counter
   */
  last_read_counter: number | null
  status: NfcTagStatus
  /**
   * Created At
   */
  created_at: string
}

/**
 * NfcTagStatus
 */
export type NfcTagStatus = "active" | "revoked"

/**
 * NfcTagsPublic
 */
export type NfcTagsPublic = {
  /**
   * Data
   */
  data: Array<NfcTagPublic>
  /**
   * Count
   */
  count: number
}

/**
 * PrivateUserCreate
 */
export type PrivateUserCreate = {
  /**
   * Email
   */
  email: string
  /**
   * Password
   */
  password: string
  /**
   * Full Name
   */
  full_name: string
  /**
   * Is Verified
   */
  is_verified?: boolean
}

/**
 * Token
 */
export type Token = {
  /**
   * Access Token
   */
  access_token: string
  /**
   * Token Type
   */
  token_type?: string
}

/**
 * UpdatePassword
 */
export type UpdatePassword = {
  /**
   * Current Password
   */
  current_password: string
  /**
   * New Password
   */
  new_password: string
}

/**
 * UserCreate
 */
export type UserCreate = {
  /**
   * Email
   */
  email: string
  /**
   * Is Active
   */
  is_active?: boolean
  permissions?: UserPermission
  /**
   * Full Name
   */
  full_name?: string | null
  /**
   * Password
   */
  password: string
}

/**
 * UserPermission
 */
export type UserPermission = "superuser" | "guest" | "collector"

/**
 * UserPublic
 */
export type UserPublic = {
  /**
   * Email
   */
  email: string
  /**
   * Is Active
   */
  is_active?: boolean
  permissions?: UserPermission
  /**
   * Full Name
   */
  full_name?: string | null
  /**
   * Id
   */
  id: string
}

/**
 * UserRegister
 */
export type UserRegister = {
  /**
   * Email
   */
  email: string
  /**
   * Password
   */
  password: string
  /**
   * Full Name
   */
  full_name?: string | null
}

/**
 * UserUpdate
 */
export type UserUpdate = {
  /**
   * Email
   */
  email?: string | null
  /**
   * Is Active
   */
  is_active?: boolean
  permissions?: UserPermission
  /**
   * Full Name
   */
  full_name?: string | null
  /**
   * Password
   */
  password?: string | null
}

/**
 * UserUpdateMe
 */
export type UserUpdateMe = {
  /**
   * Full Name
   */
  full_name?: string | null
  /**
   * Email
   */
  email?: string | null
}

/**
 * UsersPublic
 */
export type UsersPublic = {
  /**
   * Data
   */
  data: Array<UserPublic>
  /**
   * Count
   */
  count: number
}

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>
  /**
   * Message
   */
  msg: string
  /**
   * Error Type
   */
  type: string
}

export type LoginLoginAccessTokenData = {
  body: BodyLoginLoginAccessToken
  path?: never
  query?: never
  url: "/api/v1/login/access-token"
}

export type LoginLoginAccessTokenErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type LoginLoginAccessTokenError =
  LoginLoginAccessTokenErrors[keyof LoginLoginAccessTokenErrors]

export type LoginLoginAccessTokenResponses = {
  /**
   * Successful Response
   */
  200: Token
}

export type LoginLoginAccessTokenResponse =
  LoginLoginAccessTokenResponses[keyof LoginLoginAccessTokenResponses]

export type LoginTestTokenData = {
  body?: never
  path?: never
  query?: never
  url: "/api/v1/login/test-token"
}

export type LoginTestTokenResponses = {
  /**
   * Successful Response
   */
  200: UserPublic
}

export type LoginTestTokenResponse =
  LoginTestTokenResponses[keyof LoginTestTokenResponses]

export type LoginRecoverPasswordData = {
  body?: never
  path: {
    /**
     * Email
     */
    email: string
  }
  query?: never
  url: "/api/v1/password-recovery/{email}"
}

export type LoginRecoverPasswordErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type LoginRecoverPasswordError =
  LoginRecoverPasswordErrors[keyof LoginRecoverPasswordErrors]

export type LoginRecoverPasswordResponses = {
  /**
   * Successful Response
   */
  200: Message
}

export type LoginRecoverPasswordResponse =
  LoginRecoverPasswordResponses[keyof LoginRecoverPasswordResponses]

export type LoginResetPasswordData = {
  body: NewPassword
  path?: never
  query?: never
  url: "/api/v1/reset-password/"
}

export type LoginResetPasswordErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type LoginResetPasswordError =
  LoginResetPasswordErrors[keyof LoginResetPasswordErrors]

export type LoginResetPasswordResponses = {
  /**
   * Successful Response
   */
  200: Message
}

export type LoginResetPasswordResponse =
  LoginResetPasswordResponses[keyof LoginResetPasswordResponses]

export type LoginRecoverPasswordHtmlContentData = {
  body?: never
  path: {
    /**
     * Email
     */
    email: string
  }
  query?: never
  url: "/api/v1/password-recovery-html-content/{email}"
}

export type LoginRecoverPasswordHtmlContentErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type LoginRecoverPasswordHtmlContentError =
  LoginRecoverPasswordHtmlContentErrors[keyof LoginRecoverPasswordHtmlContentErrors]

export type LoginRecoverPasswordHtmlContentResponses = {
  /**
   * Successful Response
   */
  200: string
}

export type LoginRecoverPasswordHtmlContentResponse =
  LoginRecoverPasswordHtmlContentResponses[keyof LoginRecoverPasswordHtmlContentResponses]

export type UsersReadUsersData = {
  body?: never
  path?: never
  query?: {
    /**
     * Skip
     */
    skip?: number
    /**
     * Limit
     */
    limit?: number
  }
  url: "/api/v1/users/"
}

export type UsersReadUsersErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type UsersReadUsersError =
  UsersReadUsersErrors[keyof UsersReadUsersErrors]

export type UsersReadUsersResponses = {
  /**
   * Successful Response
   */
  200: UsersPublic
}

export type UsersReadUsersResponse =
  UsersReadUsersResponses[keyof UsersReadUsersResponses]

export type UsersCreateUserData = {
  body: UserCreate
  path?: never
  query?: never
  url: "/api/v1/users/"
}

export type UsersCreateUserErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type UsersCreateUserError =
  UsersCreateUserErrors[keyof UsersCreateUserErrors]

export type UsersCreateUserResponses = {
  /**
   * Successful Response
   */
  200: UserPublic
}

export type UsersCreateUserResponse =
  UsersCreateUserResponses[keyof UsersCreateUserResponses]

export type UsersDeleteUserMeData = {
  body?: never
  path?: never
  query?: never
  url: "/api/v1/users/me"
}

export type UsersDeleteUserMeResponses = {
  /**
   * Successful Response
   */
  200: Message
}

export type UsersDeleteUserMeResponse =
  UsersDeleteUserMeResponses[keyof UsersDeleteUserMeResponses]

export type UsersReadUserMeData = {
  body?: never
  path?: never
  query?: never
  url: "/api/v1/users/me"
}

export type UsersReadUserMeResponses = {
  /**
   * Successful Response
   */
  200: UserPublic
}

export type UsersReadUserMeResponse =
  UsersReadUserMeResponses[keyof UsersReadUserMeResponses]

export type UsersUpdateUserMeData = {
  body: UserUpdateMe
  path?: never
  query?: never
  url: "/api/v1/users/me"
}

export type UsersUpdateUserMeErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type UsersUpdateUserMeError =
  UsersUpdateUserMeErrors[keyof UsersUpdateUserMeErrors]

export type UsersUpdateUserMeResponses = {
  /**
   * Successful Response
   */
  200: UserPublic
}

export type UsersUpdateUserMeResponse =
  UsersUpdateUserMeResponses[keyof UsersUpdateUserMeResponses]

export type UsersUpdatePasswordMeData = {
  body: UpdatePassword
  path?: never
  query?: never
  url: "/api/v1/users/me/password"
}

export type UsersUpdatePasswordMeErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type UsersUpdatePasswordMeError =
  UsersUpdatePasswordMeErrors[keyof UsersUpdatePasswordMeErrors]

export type UsersUpdatePasswordMeResponses = {
  /**
   * Successful Response
   */
  200: Message
}

export type UsersUpdatePasswordMeResponse =
  UsersUpdatePasswordMeResponses[keyof UsersUpdatePasswordMeResponses]

export type UsersRegisterUserData = {
  body: UserRegister
  path?: never
  query?: never
  url: "/api/v1/users/signup"
}

export type UsersRegisterUserErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type UsersRegisterUserError =
  UsersRegisterUserErrors[keyof UsersRegisterUserErrors]

export type UsersRegisterUserResponses = {
  /**
   * Successful Response
   */
  200: UserPublic
}

export type UsersRegisterUserResponse =
  UsersRegisterUserResponses[keyof UsersRegisterUserResponses]

export type UsersConfirmEmailData = {
  body: EmailConfirmation
  path?: never
  query?: never
  url: "/api/v1/users/confirm-email"
}

export type UsersConfirmEmailErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type UsersConfirmEmailError =
  UsersConfirmEmailErrors[keyof UsersConfirmEmailErrors]

export type UsersConfirmEmailResponses = {
  /**
   * Successful Response
   */
  200: Message
}

export type UsersConfirmEmailResponse =
  UsersConfirmEmailResponses[keyof UsersConfirmEmailResponses]

export type UsersDeleteUserData = {
  body?: never
  path: {
    /**
     * User Id
     */
    user_id: string
  }
  query?: never
  url: "/api/v1/users/{user_id}"
}

export type UsersDeleteUserErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type UsersDeleteUserError =
  UsersDeleteUserErrors[keyof UsersDeleteUserErrors]

export type UsersDeleteUserResponses = {
  /**
   * Successful Response
   */
  200: Message
}

export type UsersDeleteUserResponse =
  UsersDeleteUserResponses[keyof UsersDeleteUserResponses]

export type UsersReadUserByIdData = {
  body?: never
  path: {
    /**
     * User Id
     */
    user_id: string
  }
  query?: never
  url: "/api/v1/users/{user_id}"
}

export type UsersReadUserByIdErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type UsersReadUserByIdError =
  UsersReadUserByIdErrors[keyof UsersReadUserByIdErrors]

export type UsersReadUserByIdResponses = {
  /**
   * Successful Response
   */
  200: UserPublic
}

export type UsersReadUserByIdResponse =
  UsersReadUserByIdResponses[keyof UsersReadUserByIdResponses]

export type UsersUpdateUserData = {
  body: UserUpdate
  path: {
    /**
     * User Id
     */
    user_id: string
  }
  query?: never
  url: "/api/v1/users/{user_id}"
}

export type UsersUpdateUserErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type UsersUpdateUserError =
  UsersUpdateUserErrors[keyof UsersUpdateUserErrors]

export type UsersUpdateUserResponses = {
  /**
   * Successful Response
   */
  200: UserPublic
}

export type UsersUpdateUserResponse =
  UsersUpdateUserResponses[keyof UsersUpdateUserResponses]

export type UsersGetUserEmailStatusData = {
  body?: never
  path: {
    /**
     * User Id
     */
    user_id: string
  }
  query?: never
  url: "/api/v1/users/{user_id}/email-status"
}

export type UsersGetUserEmailStatusErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type UsersGetUserEmailStatusError =
  UsersGetUserEmailStatusErrors[keyof UsersGetUserEmailStatusErrors]

export type UsersGetUserEmailStatusResponses = {
  /**
   * Response Users-Get User Email Status
   *
   * Successful Response
   */
  200: EmailLogPublic | null
}

export type UsersGetUserEmailStatusResponse =
  UsersGetUserEmailStatusResponses[keyof UsersGetUserEmailStatusResponses]

export type UtilsTestEmailData = {
  body?: never
  path?: never
  query: {
    /**
     * Email To
     */
    email_to: string
  }
  url: "/api/v1/utils/test-email/"
}

export type UtilsTestEmailErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type UtilsTestEmailError =
  UtilsTestEmailErrors[keyof UtilsTestEmailErrors]

export type UtilsTestEmailResponses = {
  /**
   * Successful Response
   */
  201: Message
}

export type UtilsTestEmailResponse =
  UtilsTestEmailResponses[keyof UtilsTestEmailResponses]

export type UtilsListPermissionsData = {
  body?: never
  path?: never
  query?: never
  url: "/api/v1/utils/permissions/"
}

export type UtilsListPermissionsResponses = {
  /**
   * Response Utils-List Permissions
   *
   * Successful Response
   */
  200: Array<string>
}

export type UtilsListPermissionsResponse =
  UtilsListPermissionsResponses[keyof UtilsListPermissionsResponses]

export type ItemsReadItemsData = {
  body?: never
  path?: never
  query?: {
    /**
     * Skip
     */
    skip?: number
    /**
     * Limit
     */
    limit?: number
  }
  url: "/api/v1/items/"
}

export type ItemsReadItemsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type ItemsReadItemsError =
  ItemsReadItemsErrors[keyof ItemsReadItemsErrors]

export type ItemsReadItemsResponses = {
  /**
   * Successful Response
   */
  200: ItemsPublic
}

export type ItemsReadItemsResponse =
  ItemsReadItemsResponses[keyof ItemsReadItemsResponses]

export type ItemsCreateItemData = {
  body: ItemCreate
  path?: never
  query?: never
  url: "/api/v1/items/"
}

export type ItemsCreateItemErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type ItemsCreateItemError =
  ItemsCreateItemErrors[keyof ItemsCreateItemErrors]

export type ItemsCreateItemResponses = {
  /**
   * Successful Response
   */
  200: ItemPublic
}

export type ItemsCreateItemResponse =
  ItemsCreateItemResponses[keyof ItemsCreateItemResponses]

export type ItemsReadMyItemsData = {
  body?: never
  path?: never
  query?: {
    /**
     * Skip
     */
    skip?: number
    /**
     * Limit
     */
    limit?: number
  }
  url: "/api/v1/items/my-items/"
}

export type ItemsReadMyItemsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type ItemsReadMyItemsError =
  ItemsReadMyItemsErrors[keyof ItemsReadMyItemsErrors]

export type ItemsReadMyItemsResponses = {
  /**
   * Successful Response
   */
  200: ItemsPublic
}

export type ItemsReadMyItemsResponse =
  ItemsReadMyItemsResponses[keyof ItemsReadMyItemsResponses]

export type ItemsDeleteItemData = {
  body?: never
  path: {
    /**
     * Id
     */
    id: string
  }
  query?: never
  url: "/api/v1/items/{id}"
}

export type ItemsDeleteItemErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type ItemsDeleteItemError =
  ItemsDeleteItemErrors[keyof ItemsDeleteItemErrors]

export type ItemsDeleteItemResponses = {
  /**
   * Successful Response
   */
  200: Message
}

export type ItemsDeleteItemResponse =
  ItemsDeleteItemResponses[keyof ItemsDeleteItemResponses]

export type ItemsReadItemData = {
  body?: never
  path: {
    /**
     * Id
     */
    id: string
  }
  query?: never
  url: "/api/v1/items/{id}"
}

export type ItemsReadItemErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type ItemsReadItemError = ItemsReadItemErrors[keyof ItemsReadItemErrors]

export type ItemsReadItemResponses = {
  /**
   * Successful Response
   */
  200: ItemWithPermissions
}

export type ItemsReadItemResponse =
  ItemsReadItemResponses[keyof ItemsReadItemResponses]

export type ItemsUpdateItemData = {
  body: ItemUpdate
  path: {
    /**
     * Id
     */
    id: string
  }
  query?: never
  url: "/api/v1/items/{id}"
}

export type ItemsUpdateItemErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type ItemsUpdateItemError =
  ItemsUpdateItemErrors[keyof ItemsUpdateItemErrors]

export type ItemsUpdateItemResponses = {
  /**
   * Successful Response
   */
  200: ItemPublic
}

export type ItemsUpdateItemResponse =
  ItemsUpdateItemResponses[keyof ItemsUpdateItemResponses]

export type ImagesUploadFileData = {
  body: BodyImagesUploadFile
  path: {
    /**
     * Id
     */
    id: string
  }
  query?: never
  url: "/api/v1/images/{id}"
}

export type ImagesUploadFileErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type ImagesUploadFileError =
  ImagesUploadFileErrors[keyof ImagesUploadFileErrors]

export type ImagesUploadFileResponses = {
  /**
   * Successful Response
   */
  200: ImagePublic
}

export type ImagesUploadFileResponse =
  ImagesUploadFileResponses[keyof ImagesUploadFileResponses]

export type ImagesDeleteFileData = {
  body?: never
  path: {
    /**
     * Image Id
     */
    image_id: string
  }
  query?: never
  url: "/api/v1/images/{image_id}"
}

export type ImagesDeleteFileErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type ImagesDeleteFileError =
  ImagesDeleteFileErrors[keyof ImagesDeleteFileErrors]

export type ImagesDeleteFileResponses = {
  /**
   * Response Images-Delete File
   *
   * Successful Response
   */
  200: {
    [key: string]: string
  }
}

export type ImagesDeleteFileResponse =
  ImagesDeleteFileResponses[keyof ImagesDeleteFileResponses]

export type ImagesGetImageData = {
  body?: never
  path: {
    /**
     * Image Id
     */
    image_id: string
  }
  query?: never
  url: "/api/v1/images/{image_id}"
}

export type ImagesGetImageErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type ImagesGetImageError =
  ImagesGetImageErrors[keyof ImagesGetImageErrors]

export type ImagesGetImageResponses = {
  /**
   * Successful Response
   */
  200: ImagePublic
}

export type ImagesGetImageResponse =
  ImagesGetImageResponses[keyof ImagesGetImageResponses]

export type ImagesDeleteItemImagesData = {
  body?: never
  path: {
    /**
     * Item Id
     */
    item_id: string
  }
  query?: never
  url: "/api/v1/images/item/{item_id}"
}

export type ImagesDeleteItemImagesErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type ImagesDeleteItemImagesError =
  ImagesDeleteItemImagesErrors[keyof ImagesDeleteItemImagesErrors]

export type ImagesDeleteItemImagesResponses = {
  /**
   * Response Images-Delete Item Images
   *
   * Successful Response
   */
  200: {
    [key: string]: string
  }
}

export type ImagesDeleteItemImagesResponse =
  ImagesDeleteItemImagesResponses[keyof ImagesDeleteItemImagesResponses]

export type ImagesGetItemImagesData = {
  body?: never
  path: {
    /**
     * Item Id
     */
    item_id: string
  }
  query?: never
  url: "/api/v1/images/item/{item_id}"
}

export type ImagesGetItemImagesErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type ImagesGetItemImagesError =
  ImagesGetItemImagesErrors[keyof ImagesGetItemImagesErrors]

export type ImagesGetItemImagesResponses = {
  /**
   * Successful Response
   */
  200: ImagesPublic
}

export type ImagesGetItemImagesResponse =
  ImagesGetItemImagesResponses[keyof ImagesGetItemImagesResponses]

export type ImagesDownloadImageData = {
  body?: never
  path: {
    /**
     * Image Id
     */
    image_id: string
  }
  query?: never
  url: "/api/v1/images/download/{image_id}"
}

export type ImagesDownloadImageErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type ImagesDownloadImageError =
  ImagesDownloadImageErrors[keyof ImagesDownloadImageErrors]

export type ImagesDownloadImageResponses = {
  /**
   * Successful Response
   */
  200: unknown
}

export type LogsGetRecentLogsData = {
  body?: never
  path?: never
  query?: {
    /**
     * Limit
     */
    limit?: number
    /**
     * Level
     */
    level?: string | null
  }
  url: "/api/v1/logs/recent"
}

export type LogsGetRecentLogsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type LogsGetRecentLogsError =
  LogsGetRecentLogsErrors[keyof LogsGetRecentLogsErrors]

export type LogsGetRecentLogsResponses = {
  /**
   * Response Logs-Get Recent Logs
   *
   * Successful Response
   */
  200: {
    [key: string]: unknown
  }
}

export type LogsGetRecentLogsResponse =
  LogsGetRecentLogsResponses[keyof LogsGetRecentLogsResponses]

export type LogsClearLogsData = {
  body?: never
  path?: never
  query?: never
  url: "/api/v1/logs/clear"
}

export type LogsClearLogsResponses = {
  /**
   * Response Logs-Clear Logs
   *
   * Successful Response
   */
  200: {
    [key: string]: string
  }
}

export type LogsClearLogsResponse =
  LogsClearLogsResponses[keyof LogsClearLogsResponses]

export type LogsGetLogStatsData = {
  body?: never
  path?: never
  query?: never
  url: "/api/v1/logs/stats"
}

export type LogsGetLogStatsResponses = {
  /**
   * Response Logs-Get Log Stats
   *
   * Successful Response
   */
  200: {
    [key: string]: unknown
  }
}

export type LogsGetLogStatsResponse =
  LogsGetLogStatsResponses[keyof LogsGetLogStatsResponses]

export type ModelsGetModelData = {
  body?: never
  path: {
    /**
     * Item Id
     */
    item_id: string
    /**
     * User Id
     */
    user_id: string
  }
  query?: never
  url: "/api/v1/models/{item_id}/{user_id}"
}

export type ModelsGetModelErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type ModelsGetModelError =
  ModelsGetModelErrors[keyof ModelsGetModelErrors]

export type ModelsGetModelResponses = {
  /**
   * Response Models-Get Model
   *
   * Successful Response
   */
  200: {
    [key: string]: string | null
  }
}

export type ModelsGetModelResponse =
  ModelsGetModelResponses[keyof ModelsGetModelResponses]

export type ModelsUploadModelData = {
  body: BodyModelsUploadModel
  path: {
    /**
     * Item Id
     */
    item_id: string
    /**
     * User Id
     */
    user_id: string
  }
  query?: never
  url: "/api/v1/models/{item_id}/{user_id}"
}

export type ModelsUploadModelErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type ModelsUploadModelError =
  ModelsUploadModelErrors[keyof ModelsUploadModelErrors]

export type ModelsUploadModelResponses = {
  /**
   * Response Models-Upload Model
   *
   * Successful Response
   */
  200: {
    [key: string]: string
  }
}

export type ModelsUploadModelResponse =
  ModelsUploadModelResponses[keyof ModelsUploadModelResponses]

export type ModelsDeleteModelData = {
  body?: never
  path: {
    /**
     * Item Id
     */
    item_id: string
    /**
     * User Id
     */
    user_id: string
    /**
     * File Name
     */
    file_name: string
  }
  query?: never
  url: "/api/v1/models/{item_id}/{user_id}/{file_name}"
}

export type ModelsDeleteModelErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type ModelsDeleteModelError =
  ModelsDeleteModelErrors[keyof ModelsDeleteModelErrors]

export type ModelsDeleteModelResponses = {
  /**
   * Response Models-Delete Model
   *
   * Successful Response
   */
  200: {
    [key: string]: string
  }
}

export type ModelsDeleteModelResponse =
  ModelsDeleteModelResponses[keyof ModelsDeleteModelResponses]

export type ModelsDownloadModelData = {
  body?: never
  path: {
    /**
     * Item Id
     */
    item_id: string
    /**
     * User Id
     */
    user_id: string
    /**
     * File Name
     */
    file_name: string
  }
  query?: never
  url: "/api/v1/models/{item_id}/{user_id}/{file_name}"
}

export type ModelsDownloadModelErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type ModelsDownloadModelError =
  ModelsDownloadModelErrors[keyof ModelsDownloadModelErrors]

export type ModelsDownloadModelResponses = {
  /**
   * Successful Response
   */
  200: unknown
}

export type ModelsDeleteItemModelData = {
  body?: never
  path: {
    /**
     * Item Id
     */
    item_id: string
  }
  query?: never
  url: "/api/v1/models/{item_id}"
}

export type ModelsDeleteItemModelErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type ModelsDeleteItemModelError =
  ModelsDeleteItemModelErrors[keyof ModelsDeleteItemModelErrors]

export type ModelsDeleteItemModelResponses = {
  /**
   * Response Models-Delete Item Model
   *
   * Successful Response
   */
  200: {
    [key: string]: string
  }
}

export type ModelsDeleteItemModelResponse =
  ModelsDeleteItemModelResponses[keyof ModelsDeleteItemModelResponses]

export type PaymentsCreateCheckoutSessionData = {
  body: CheckoutRequest
  path?: never
  query?: never
  url: "/api/v1/payments/create-checkout-session"
}

export type PaymentsCreateCheckoutSessionErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type PaymentsCreateCheckoutSessionError =
  PaymentsCreateCheckoutSessionErrors[keyof PaymentsCreateCheckoutSessionErrors]

export type PaymentsCreateCheckoutSessionResponses = {
  /**
   * Successful Response
   */
  200: CheckoutResponse
}

export type PaymentsCreateCheckoutSessionResponse =
  PaymentsCreateCheckoutSessionResponses[keyof PaymentsCreateCheckoutSessionResponses]

export type PaymentsPaymentSuccessData = {
  body?: never
  path?: never
  query: {
    /**
     * Session Id
     */
    session_id: string
  }
  url: "/api/v1/payments/success"
}

export type PaymentsPaymentSuccessErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type PaymentsPaymentSuccessError =
  PaymentsPaymentSuccessErrors[keyof PaymentsPaymentSuccessErrors]

export type PaymentsPaymentSuccessResponses = {
  /**
   * Response Payments-Payment Success
   *
   * Successful Response
   */
  200: unknown
}

export type PaymentsPaymentCancelData = {
  body?: never
  path?: never
  query?: never
  url: "/api/v1/payments/cancel"
}

export type PaymentsPaymentCancelResponses = {
  /**
   * Response Payments-Payment Cancel
   *
   * Successful Response
   */
  200: unknown
}

export type PaymentsStripeWebhookData = {
  body?: never
  path?: never
  query?: never
  url: "/api/v1/payments/webhook"
}

export type PaymentsStripeWebhookResponses = {
  /**
   * Response Payments-Stripe Webhook
   *
   * Successful Response
   */
  200: unknown
}

export type PaymentsGetStripeConfigData = {
  body?: never
  path?: never
  query?: never
  url: "/api/v1/payments/config"
}

export type PaymentsGetStripeConfigResponses = {
  /**
   * Response Payments-Get Stripe Config
   *
   * Successful Response
   */
  200: unknown
}

export type NavigationGetNavigationItemsData = {
  body?: never
  headers?: {
    /**
     * Authorization
     */
    Authorization?: string | null
  }
  path?: never
  query?: never
  url: "/api/v1/navigation/"
}

export type NavigationGetNavigationItemsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type NavigationGetNavigationItemsError =
  NavigationGetNavigationItemsErrors[keyof NavigationGetNavigationItemsErrors]

export type NavigationGetNavigationItemsResponses = {
  /**
   * Response Navigation-Get Navigation Items
   *
   * Successful Response
   */
  200: Array<NavigationItem>
}

export type NavigationGetNavigationItemsResponse =
  NavigationGetNavigationItemsResponses[keyof NavigationGetNavigationItemsResponses]

export type NfcVerifyTagData = {
  body?: never
  path?: never
  query: {
    /**
     * Uid
     */
    uid: string
    /**
     * Picc
     */
    picc: string
    /**
     * Cmac
     */
    cmac: string
    /**
     * Enc
     */
    enc?: string | null
  }
  url: "/api/v1/nfc/verify"
}

export type NfcVerifyTagErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type NfcVerifyTagError = NfcVerifyTagErrors[keyof NfcVerifyTagErrors]

export type NfcVerifyTagResponses = {
  /**
   * Successful Response
   */
  200: unknown
}

export type NfcListTagsData = {
  body?: never
  path?: never
  query?: {
    /**
     * Skip
     */
    skip?: number
    /**
     * Limit
     */
    limit?: number
  }
  url: "/api/v1/nfc/tags"
}

export type NfcListTagsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type NfcListTagsError = NfcListTagsErrors[keyof NfcListTagsErrors]

export type NfcListTagsResponses = {
  /**
   * Successful Response
   */
  200: NfcTagsPublic
}

export type NfcListTagsResponse =
  NfcListTagsResponses[keyof NfcListTagsResponses]

export type NfcRegisterTagData = {
  body: NfcTagCreate
  path?: never
  query?: never
  url: "/api/v1/nfc/tags"
}

export type NfcRegisterTagErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type NfcRegisterTagError =
  NfcRegisterTagErrors[keyof NfcRegisterTagErrors]

export type NfcRegisterTagResponses = {
  /**
   * Successful Response
   */
  200: NfcTagPublic
}

export type NfcRegisterTagResponse =
  NfcRegisterTagResponses[keyof NfcRegisterTagResponses]

export type NfcListUntaggedItemsData = {
  body?: never
  path?: never
  query?: {
    /**
     * Skip
     */
    skip?: number
    /**
     * Limit
     */
    limit?: number
  }
  url: "/api/v1/nfc/untagged-items"
}

export type NfcListUntaggedItemsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type NfcListUntaggedItemsError =
  NfcListUntaggedItemsErrors[keyof NfcListUntaggedItemsErrors]

export type NfcListUntaggedItemsResponses = {
  /**
   * Successful Response
   */
  200: ItemsPublic
}

export type NfcListUntaggedItemsResponse =
  NfcListUntaggedItemsResponses[keyof NfcListUntaggedItemsResponses]

export type NfcRevokeTagData = {
  body?: never
  path: {
    /**
     * Uid
     */
    uid: string
  }
  query?: never
  url: "/api/v1/nfc/tags/{uid}"
}

export type NfcRevokeTagErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type NfcRevokeTagError = NfcRevokeTagErrors[keyof NfcRevokeTagErrors]

export type NfcRevokeTagResponses = {
  /**
   * Successful Response
   */
  200: Message
}

export type NfcRevokeTagResponse =
  NfcRevokeTagResponses[keyof NfcRevokeTagResponses]

export type PrivateCreateUserData = {
  body: PrivateUserCreate
  path?: never
  query?: never
  url: "/api/v1/private/users/"
}

export type PrivateCreateUserErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type PrivateCreateUserError =
  PrivateCreateUserErrors[keyof PrivateCreateUserErrors]

export type PrivateCreateUserResponses = {
  /**
   * Successful Response
   */
  200: UserPublic
}

export type PrivateCreateUserResponse =
  PrivateCreateUserResponses[keyof PrivateCreateUserResponses]

export type UsersApiCurrentUserData = {
  body?: never
  path?: never
  query?: never
  url: "/api/currentUser"
}

export type UsersApiCurrentUserResponses = {
  /**
   * Successful Response
   */
  200: UserPublic
}

export type UsersApiCurrentUserResponse =
  UsersApiCurrentUserResponses[keyof UsersApiCurrentUserResponses]
