"""priviliges -> permissions

Revision ID: 4be7250b4d82
Revises: 6e2c4bd79d36
Create Date: 2025-01-23 17:41:56.846048

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = "4be7250b4d82"
down_revision = "6e2c4bd79d36"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "permissions", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True
        ),
    )
    op.drop_column("user", "privileges")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "privileges", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("user", "permissions")
    # ### end Alembic commands ###
