"""add NFT columns to item

Revision ID: 5a8aa0b4a654
Revises: 09465fcadea9
Create Date: 2025-07-23 10:53:26.788476

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5a8aa0b4a654'
down_revision = '09465fcadea9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chunks')
    op.add_column('item', sa.Column('nft_token_id', sa.Integer(), nullable=True))
    op.add_column('item', sa.Column('nft_contract_address', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('item', sa.Column('nft_transaction_hash', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('item', sa.Column('nft_metadata_uri', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    op.add_column('item', sa.Column('is_nft_enabled', sa.Boolean(), nullable=False))
    op.alter_column('user', 'permissions',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'permissions',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('item', 'is_nft_enabled')
    op.drop_column('item', 'nft_metadata_uri')
    op.drop_column('item', 'nft_transaction_hash')
    op.drop_column('item', 'nft_contract_address')
    op.drop_column('item', 'nft_token_id')
    op.create_table('chunks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('chunk', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('vec', postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='chunks_pkey')
    )
    # ### end Alembic commands ###
