"""Add columns to item

Revision ID: 6035b3e7b95a
Revises: 06e147cc51b7
Create Date: 2025-01-13 17:50:38.579555

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '6035b3e7b95a'
down_revision = '06e147cc51b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('images', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('item', sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('item', sa.Column('certificate', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'certificate')
    op.drop_column('item', 'model')
    op.drop_column('item', 'images')
    # ### end Alembic commands ###
