"""add producer/review tables and item.producer_id

Revision ID: 6c75cd59b880
Revises: 1b2c3d4e5f67
Create Date: 2025-08-21 20:21:53.596710

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '6c75cd59b880'
down_revision = '1b2c3d4e5f67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('producer',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('review_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('producer_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['producer_id'], ['producer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('item', sa.Column('producer_id', sa.Uuid(), nullable=True))
    op.drop_constraint(op.f('item_variant_of_fkey'), 'item', type_='foreignkey')
    op.drop_constraint(op.f('item_owner_id_fkey'), 'item', type_='foreignkey')
    op.create_foreign_key(None, 'item', 'item', ['variant_of'], ['id'])
    op.create_foreign_key(None, 'item', 'producer', ['producer_id'], ['id'])
    op.create_foreign_key(None, 'item', 'user', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.create_foreign_key(op.f('item_owner_id_fkey'), 'item', 'user', ['owner_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('item_variant_of_fkey'), 'item', 'item', ['variant_of'], ['id'], ondelete='SET NULL')
    op.drop_column('item', 'producer_id')
    op.drop_table('review')
    op.drop_table('producer')
    # ### end Alembic commands ###
