"""remove columns and add priviliges

Revision ID: 6e2c4bd79d36
Revises: 6035b3e7b95a
Create Date: 2025-01-23 16:41:50.801774

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = "6e2c4bd79d36"
down_revision = "6035b3e7b95a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "privileges", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True
        ),
    )
    op.drop_column("user", "is_superuser")
    op.drop_column("user", "has_privileges")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "has_privileges",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "user",
        sa.Column("is_superuser", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.drop_column("user", "privileges")
    # ### end Alembic commands ###
