/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutImport } from './routes/_layout'
import { Route as LayoutIndexImport } from './routes/_layout/index'
import { Route as LayoutSuadminImport } from './routes/_layout/suadmin'
import { Route as LayoutSettingsImport } from './routes/_layout/settings'
import { Route as LayoutItemImport } from './routes/_layout/item'
import { Route as LayoutGalleryImport } from './routes/_layout/gallery'
import { Route as LayoutCreateitemImport } from './routes/_layout/createitem'
import { Route as LayoutBusinessplanImport } from './routes/_layout/businessplan'

// Create/Update Routes

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutSuadminRoute = LayoutSuadminImport.update({
  path: '/suadmin',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutSettingsRoute = LayoutSettingsImport.update({
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutItemRoute = LayoutItemImport.update({
  path: '/item',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutGalleryRoute = LayoutGalleryImport.update({
  path: '/gallery',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutCreateitemRoute = LayoutCreateitemImport.update({
  path: '/createitem',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutBusinessplanRoute = LayoutBusinessplanImport.update({
  path: '/businessplan',
  getParentRoute: () => LayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/_layout/businessplan': {
      preLoaderRoute: typeof LayoutBusinessplanImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/createitem': {
      preLoaderRoute: typeof LayoutCreateitemImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/gallery': {
      preLoaderRoute: typeof LayoutGalleryImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/item': {
      preLoaderRoute: typeof LayoutItemImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/settings': {
      preLoaderRoute: typeof LayoutSettingsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/suadmin': {
      preLoaderRoute: typeof LayoutSuadminImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/': {
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  LayoutRoute.addChildren([
    LayoutBusinessplanRoute,
    LayoutCreateitemRoute,
    LayoutGalleryRoute,
    LayoutItemRoute,
    LayoutSettingsRoute,
    LayoutSuadminRoute,
    LayoutIndexRoute,
  ]),
])

/* prettier-ignore-end */
